[server]
port = 8000
run_mode = "release"
read_timeout = 60
write_timeout = 60

[mysql]
# 按需设置超时时间
dsn="root:123456@tcp(127.0.0.1:3306)/wxw?timeout=500ms&readTimeout=500ms&writeTimeout=100ms&charset=utf8mb4&parseTime=True&loc=Local"
max_idle_connects = 20
max_open_connects = 20
# gorm 日志模式
log_mode = true

