system:
  mode: 'development'

log:
  prefix: '[MY-LOG] '
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

mylog:
  level: 'debug'
  prefix: '[MY-LOG]'
  file_path: 'log'
  file_name: 'mylog.log'
  max_file_size: 10485760
  max_age: 24